"""
03_regression_mean.py
---------------------
Applies empirical Bayes regression to the mean for each rate statistic.

Method:
  For a counting-stat rate r = k/n, the regressed estimate is:
      r_reg = (k + m * r_lg) / (n + m)
  where r_lg is the PA/IP-weighted league average for that season and
  m is the regression coefficient — the number of PA/IP at which a player
  is 50% signal, 50% league average. m is estimated from the data using
  the method-of-moments on the cross-sectional variance.

For stats that are not simple k/n rates (ISO, wRC+, WAR), we use
z-score shrinkage: r_reg = r_obs * (1 - lambda) + r_lg * lambda,
where lambda = m / (n + m).

Outputs:
  data/hitters_regressed.csv
  data/pitchers_regressed.csv
"""

import numpy as np
import pandas as pd

DATA_DIR = "data"

hitters = pd.read_csv(f"{DATA_DIR}/hitters_clean.csv")
pitchers = pd.read_csv(f"{DATA_DIR}/pitchers_clean.csv")
league_avg_h = pd.read_csv(f"{DATA_DIR}/league_avgs_hitters.csv")
league_avg_p = pd.read_csv(f"{DATA_DIR}/league_avgs_pitchers.csv")


# =========================================================
# REGRESSION COEFFICIENTS (m values)
# =========================================================

# m-values are loaded from data/tuned_m_values.csv if available (generated by
# 04b_tune_regression.py). Otherwise falls back to literature-informed defaults.
#
# Key finding: for KBO qualified starters (PA ≥ 300, IP ≥ 100), tuned m-values
# converge to ~1, indicating observed rates are already reliable at these sample
# sizes. The regression component contributes minimally; multi-year weighting
# and age adjustment drive the Marcel benefit for this population.

import os as _os
_tuned_path = "data/tuned_m_values.csv"
if _os.path.exists(_tuned_path):
    _tuned = pd.read_csv(_tuned_path)
    HITTER_M  = dict(zip(_tuned[_tuned["group"]=="hitter"]["stat"],  _tuned[_tuned["group"]=="hitter"]["best_m"]))
    PITCHER_M = dict(zip(_tuned[_tuned["group"]=="pitcher"]["stat"], _tuned[_tuned["group"]=="pitcher"]["best_m"]))
    print(f"Loaded tuned m-values from {_tuned_path}")
else:
    # Literature-informed defaults (MLB-based, used before KBO tuning)
    HITTER_M = {
        "BB_pct": 200, "K_pct": 60,  "HR_pct": 550, "ISO": 300,
        "wOBA":   200, "OBP":   200, "SLG":    300, "wRC+": 300,
    }
    PITCHER_M = {
        "K_pct": 70, "BB_pct": 170, "HR_per9": 700, "K_minus_BB": 170,
        "ERA":   900, "FIP":    400, "WHIP":    300,
    }
    print("Using literature-informed m-values (run 04b_tune_regression.py to tune)")


# =========================================================
# CORE REGRESSION FUNCTION
# =========================================================

def regress_to_mean(df, league_avg_df, stat_cols, m_vals, pt_col):
    """
    Shrink each player's observed rate toward the season league average.
    Returns df with new columns: {stat}_reg for each stat in stat_cols.
    """
    df = df.merge(league_avg_df[["season"] + stat_cols], on="season",
                  how="left", suffixes=("", "_lg"))

    for stat in stat_cols:
        m = m_vals.get(stat, 300)
        lg_col = stat + "_lg"

        obs = df[stat]
        lg  = df[lg_col]
        n   = df[pt_col]

        # Shrinkage weight: as n → ∞, weight → 1 (trust observed)
        shrinkage = n / (n + m)
        df[stat + "_reg"] = shrinkage * obs + (1 - shrinkage) * lg

    # Drop the temporary _lg columns
    df = df.drop(columns=[s + "_lg" for s in stat_cols])
    return df


# =========================================================
# APPLY
# =========================================================

hitters_reg = regress_to_mean(
    hitters, league_avg_h,
    stat_cols=list(HITTER_M.keys()),
    m_vals=HITTER_M,
    pt_col="PA"
)

pitchers_reg = regress_to_mean(
    pitchers, league_avg_p,
    stat_cols=list(PITCHER_M.keys()),
    m_vals=PITCHER_M,
    pt_col="IP"
)


# =========================================================
# DIAGNOSTICS
# =========================================================

def shrinkage_summary(df, stats, pt_col, m_vals):
    print(f"\n{'Stat':<14} {'m':>6} {'Mean PA/IP':>12} {'Avg Shrinkage':>15} {'Obs→Reg Corr':>14}")
    print("-" * 65)
    for stat in stats:
        m = m_vals[stat]
        avg_n = df[pt_col].mean()
        avg_shrink = (df[pt_col] / (df[pt_col] + m)).mean()
        corr = df[[stat, stat + "_reg"]].corr().iloc[0, 1]
        print(f"{stat:<14} {m:>6} {avg_n:>12.0f} {avg_shrink:>14.3f}  {corr:>13.4f}")

print("=== HITTER REGRESSION SUMMARY ===")
shrinkage_summary(hitters_reg, list(HITTER_M.keys()), "PA", HITTER_M)

print("\n=== PITCHER REGRESSION SUMMARY ===")
shrinkage_summary(pitchers_reg, list(PITCHER_M.keys()), "IP", PITCHER_M)


# =========================================================
# SAVE
# =========================================================

hitters_reg.to_csv(f"{DATA_DIR}/hitters_regressed.csv", index=False)
pitchers_reg.to_csv(f"{DATA_DIR}/pitchers_regressed.csv", index=False)

print("\n=== REGRESSION TO MEAN COMPLETE ===")
print(f"Hitters: {len(hitters_reg)} rows")
print(f"Pitchers: {len(pitchers_reg)} rows")
